mv Slide1.PNG address_serial1.PNG
mv Slide10.PNG address_serial10.PNG
mv Slide11.PNG address_serial11.PNG
mv Slide12.PNG address_serial12.PNG
mv Slide13.PNG address_serial13.PNG
mv Slide14.PNG address_serial14.PNG
mv Slide15.PNG address_serial15.PNG
mv Slide16.PNG address_serial16.PNG
mv Slide17.PNG address_serial17.PNG
mv Slide18.PNG address_serial18.PNG
mv Slide19.PNG address_serial19.PNG
mv Slide2.PNG address_serial2.PNG
mv Slide20.PNG address_serial20.PNG
mv Slide21.PNG address_serial21.PNG
mv Slide22.PNG address_serial22.PNG
mv Slide23.PNG address_serial23.PNG
mv Slide24.PNG address_serial24.PNG
mv Slide25.PNG address_serial25.PNG
mv Slide26.PNG address_serial26.PNG
mv Slide27.PNG address_serial27.PNG
mv Slide28.PNG address_serial28.PNG
mv Slide29.PNG address_serial29.PNG
mv Slide3.PNG address_serial3.PNG
mv Slide30.PNG address_serial30.PNG
mv Slide31.PNG address_serial31.PNG
mv Slide32.PNG address_serial32.PNG
mv Slide33.PNG address_serial33.PNG
mv Slide4.PNG address_serial4.PNG
mv Slide5.PNG address_serial5.PNG
mv Slide6.PNG address_serial6.PNG
mv Slide7.PNG address_serial7.PNG
mv Slide8.PNG address_serial8.PNG
mv Slide9.PNG address_serial9.PNG
mv this.sh this.sh
